# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crabctl < Formula
  desc "Manage Claude Code sessions in tmux"
  homepage "https://github.com/curusarn/crabctl"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.2/crabctl_0.1.2_darwin_amd64.tar.gz"
      sha256 "b17d69ee5c8d1d1210ac8084e58f4314c56654d84fe756c16edcd926bab4a636"

      def install
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.2/crabctl_0.1.2_darwin_arm64.tar.gz"
      sha256 "dde5bf5164deb556d28e7a6b4adeeb4364bba9b504f76e5ba5bc0fb3db4ef959"

      def install
        bin.install "crabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.2/crabctl_0.1.2_linux_amd64.tar.gz"
      sha256 "0f2d04e427f90efe4c752e060d82183a21d662a65ac4e83d17fecb03ae270bf4"
      def install
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.2/crabctl_0.1.2_linux_arm64.tar.gz"
      sha256 "1228d5c83fdcf038a5a8e30452ade7c7176225908492c12115170027d4cf3bf1"
      def install
        bin.install "crabctl"
      end
    end
  end
end
