# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "Claude usage limits for multiple accounts, side by side"
  homepage "https://github.com/curusarn/claude-limits"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.3.0/claude-limits_0.3.0_darwin_amd64.tar.gz"
      sha256 "f6b195e2ba27885e07e0516fd4c1b7b02bf61e835cb47c418c9257b1bed41ac5"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.3.0/claude-limits_0.3.0_darwin_arm64.tar.gz"
      sha256 "790b141aa4a6e9285fa1d3185eed8cbb3aadcbed703f9711aca49b1be2205040"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.3.0/claude-limits_0.3.0_linux_amd64.tar.gz"
      sha256 "9128a863e0c900683e1e4f1972368de1594d92068e312ac4f68c80b1d3668b33"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.3.0/claude-limits_0.3.0_linux_arm64.tar.gz"
      sha256 "7efe4cfd8803b9359e5a3018ed7fad464b41333b085358dcac25418ae2d4b141"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end
end
