# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "Claude usage limits for multiple accounts, side by side"
  homepage "https://github.com/curusarn/claude-limits"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.1.0/claude-limits_0.1.0_darwin_amd64.tar.gz"
      sha256 "9cd434952dde179efb97be50de519cc26128d58c0cb9884ccd1637b2404787ca"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.1.0/claude-limits_0.1.0_darwin_arm64.tar.gz"
      sha256 "d4d4554762862f118604d2119ec33e9d92bb41e3b162d7bcd3ff8dc0379fb406"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.1.0/claude-limits_0.1.0_linux_amd64.tar.gz"
      sha256 "6205bfb094327d4758374a079e316962c18ac56c7f57fc6bb8eeaaf8bee336ae"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.1.0/claude-limits_0.1.0_linux_arm64.tar.gz"
      sha256 "731d21cfd3331d18ae03d9fcf957e59b3651f73cc7f3be0a73466d9f56e88c24"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end
end
