# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "Claude usage limits for multiple accounts, side by side"
  homepage "https://github.com/curusarn/claude-limits"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.2.1/claude-limits_0.2.1_darwin_amd64.tar.gz"
      sha256 "73a34e8831815494721f94429b3558047da39c8aa77780b3941acc1913515338"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.2.1/claude-limits_0.2.1_darwin_arm64.tar.gz"
      sha256 "9ae64c051ff7bfe925fd04677c67e15e5830aa06255575a0f8d96cc4ec2bd628"

      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.2.1/claude-limits_0.2.1_linux_amd64.tar.gz"
      sha256 "3f7889139d16e72a499aa92371ad7a14a6a19aed737c7f08c3831fc7eecee5f6"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/claude-limits/releases/download/v0.2.1/claude-limits_0.2.1_linux_arm64.tar.gz"
      sha256 "fbae8bc198b86c3a6db0c1f5cbda4f1d860126c7f80484edb4872cd7393aad80"
      define_method(:install) do
        bin.install "claude-limits"
      end
    end
  end
end
