# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crabctl < Formula
  desc "Manage Claude Code sessions in tmux"
  homepage "https://github.com/curusarn/crabctl"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/crabctl/releases/download/v0.2.2/crabctl_0.2.2_darwin_amd64.tar.gz"
      sha256 "6b6af8c0fe09388e8231f8b9efec6374916a777bcd112607a5d7f14630426d87"

      define_method(:install) do
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/crabctl/releases/download/v0.2.2/crabctl_0.2.2_darwin_arm64.tar.gz"
      sha256 "b23e7adcd09dc9ee409647a79e9b53df61f3becea98cb43a39a7e8b76ea92683"

      define_method(:install) do
        bin.install "crabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.2.2/crabctl_0.2.2_linux_amd64.tar.gz"
      sha256 "81f63fb34cf799d4d3c24aa1252e06ef85a7f79556455f080cd2a9c4fbc4e56b"
      define_method(:install) do
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.2.2/crabctl_0.2.2_linux_arm64.tar.gz"
      sha256 "e68742e573b3147dd45da0ef1395bea01b70315807eb3816cc331010b808ffbf"
      define_method(:install) do
        bin.install "crabctl"
      end
    end
  end
end
