# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crabctl < Formula
  desc "Manage Claude Code sessions in tmux"
  homepage "https://github.com/curusarn/crabctl"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.3/crabctl_0.1.3_darwin_amd64.tar.gz"
      sha256 "c068f688cc6b1819baa43d70f8aff45f7a0ae1ebfe5f7bc5e96006be8f08b74d"

      def install
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.3/crabctl_0.1.3_darwin_arm64.tar.gz"
      sha256 "60423b8d5cb5cc451b344e05c84cbb1b0816ef8f9dabb2dab2eef434f0721165"

      def install
        bin.install "crabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.3/crabctl_0.1.3_linux_amd64.tar.gz"
      sha256 "cadc63a402f6d916d889ba7bfc4becf7c3bfe3b1c92c720d8cf916b838ed0c74"
      def install
        bin.install "crabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curusarn/crabctl/releases/download/v0.1.3/crabctl_0.1.3_linux_arm64.tar.gz"
      sha256 "f0e83e8d6acf31ed08352ea2d924318dc53a810c027514f6f8dfa99eda6539e4"
      def install
        bin.install "crabctl"
      end
    end
  end
end
